# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
#[en]
#  languageCode = "en-us"
  # contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
#  contentDir = "content/zh"
  title = "FLOWERPP"
  [zh.params]
    description = "Flowerpp的站点"

  [[zh.menu.main]]
    name = "首页"
    url = "#"
    weight = 1


  [[zh.menu.main]]
    name = "博客"
    url = "#posts"
    weight = 2

  [[zh.menu.main]]
    name = "关于"
    url = "#about"
    weight = 3